services:
  # описание контейнера db
  db:
    container_name: db
    # образ, из которого должен быть запущен контейнер
    image: postgres:17.5
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
    # volume и связанная с ним директория в контейнере
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    container_name: redis
    image: redis/redis-stack:7.2.0-v15
    restart: always
    ports:
      - "6379:6379"

  market-app:
    container_name: market-app
    build:
      context: ./market
      dockerfile: Dockerfile
    image: market-app
    restart: on-failure
    env_file:
      - .env
    environment:
      - SERVER_PORT=${MARKET_SERVER_PORT}
    ports:
      - "8081:8081"
    volumes:
      - ./images:/market-app/images
    depends_on:
      - db
      - redis
      - payments-app

  payments-app:
    container_name: payments-app
    build:
      context: ./payments
      dockerfile: Dockerfile
    image: payments-app
    restart: on-failure
    env_file:
      - .env
    environment:
      - SERVER_PORT=${PAYMENTS_SERVER_PORT}
    ports:
      - "8082:8082"

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health/ready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
