server:
  port: ${SERVER_PORT}

spring:
  application:
    name: market

  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: ${KEYCLOAK_PROVIDER}
            client-id: ${KEYCLOAK_CLIENT_ID}
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            authorization-grant-type: ${KEYCLOAK_AUTHORIZATION_GRANT_TYPE}
            scope: ${KEYCLOAK_SCOPE}
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI}

  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    default-schema: ${DATASOURCE_SCHEMA_NAME}
    url: ${SPRING_LIQUIBASE_URL}
    user: ${SPRING_LIQUIBASE_USER}
    password: ${SPRING_LIQUIBASE_PASSWORD}

  webflux:
    multipart:
      max-in-memory-size: ${SPRING_WEBFLUX_MULTIPART_MAX_IN_MEMORY_SIZE}
      max-disk-usage-per-part: ${SPRING_WEBFLUX_MULTIPART_MAX_DISK_USAGE_PER_PART}
      max-parts: ${SPRING_WEBFLUX_MULTIPART_MAX_PARTS}

  http:
    codecs:
      max-in-memory-size: ${SPRING_CODEC_MAX_IN_MEMORY_SIZE}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  cache:
    redis:
      time-to-live: ${REDIS_TTL}

logging:
  level:
    ru:
      practicum: ${LOGGING_PRACTICUM_LEVEL}

image:
  path: ${IMAGE_PATH}
  public-uri-prefix: ${IMAGE_PUBLIC_URI_PREFIX}
  resource-handler-pattern: ${IMAGE_RESOURCE_HANDLER_PATTERN}

integration:
  payments:
    baseUrl: ${PAYMENTS_BASE_URL}
    web-client:
      pool:
        name: ${PAYMENTS_WEBCLIENT_POOL_NAME}
        max-connections: ${PAYMENTS_WEBCLIENT_POOL_MAX_CONNECTIONS}
        pending-acquire-timeout: ${PAYMENTS_WEBCLIENT_POOL_PENDING_ACQUIRE_TIMEOUT}
        max-idle-time: ${PAYMENTS_WEBCLIENT_POOL_MAX_IDLE_TIME}
      timeouts:
        connect-timeout-millis: ${PAYMENTS_WEBCLIENT_CONNECT_TIMEOUT_MILLIS}
        response-timeout: ${PAYMENTS_WEBCLIENT_RESPONSE_TIMEOUT}
        read-timeout: ${PAYMENTS_WEBCLIENT_READ_TIMEOUT}
        write-timeout: ${PAYMENTS_WEBCLIENT_WRITE_TIMEOUT}
